FROM nginx:alpine

# Copiar configuración personalizada de Nginx
COPY demo-docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copiar archivos del frontend desde el directorio demo-frontend/
COPY demo-frontend/ /usr/share/nginx/html/
