version: '3.8'

services:
  # 1. Base de Datos de Prueba (Simula el Servidor SQL Local en On-Premise)
  db:
    image: postgres:15-alpine
    container_name: sim-database
    environment:
      POSTGRES_DB: empresa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
    # La BD solo pertenece a la red interna local. Está aislada del exterior.
    networks:
      - on_premise_net
    # No exponemos puertos al host para garantizar el aislamiento perimetral.
    expose:
      - "5432"
    restart: unless-stopped

  # 2. Servidor Central (Simula el API Gateway en la Nube / Cloud)
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: sim-central-server
    ports:
      - "3500:3500" # Expuesto al host para simular peticiones externas e inyección de JMeter
    volumes:
      - ./server-config/agents.docker.json:/app/agents.json:ro
      - ./server-config/env.docker:/app/.env:ro
    # El servidor central pertenece únicamente a la red Cloud. No puede "ver" la BD local.
    networks:
      - cloud_net
    restart: unless-stopped

  # 3. Agente Local (Simula el cliente del túnel inverso en la red corporativa)
  agent:
    build:
      context: ../agent
      dockerfile: Dockerfile
    container_name: sim-local-agent
    depends_on:
      - db
      - server
    volumes:
      - ./agent-config/config.docker.json:/app/config.json:ro
      - ./agent-config/queries.pg.json:/app/queries.json:ro
      - ./agent-logs:/app/logs:rw
    # El Agente actúa como puente: se conecta a la red Cloud (hacia afuera, por WebSocket)
    # y se conecta a la red On-Premise (hacia adentro, para consultar la base de datos).
    # IMPORTANTE: NO expone ningún puerto al host ni a otras redes.
    networks:
      - cloud_net
      - on_premise_net
    restart: unless-stopped

networks:
  # Red virtual que simula la Nube / Internet
  cloud_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

  # Red virtual que simula la Red Local Privada (On-Premise)
  on_premise_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
